### ISSUE TITLE
Data test cases fail with bool initializer list

### ISSUE THREAD

**Issue by ShadowIce** [boostorg/test#217]
If a data test case uses boolean values directly passed to make in the BOOST_DATA_TEST_CASE macro the resulting value will be more or less random. This happens when compiling it on macOS / clang 10.0.1 / boost 1.7.0, but not on Windows with VS2017. It also doesn't happen with any other data types except bool.

```C++
constexpr bool ExpectedValues[] = { false, true, true, true, false, false};
BOOST_DATA_TEST_CASE(BoostDataTest
	, boost::unit_test::data::make({ false, true, true, true, false, false }) ^
	  boost::unit_test::data::make(ExpectedValues)
	, value, expectedValue)
{
	BOOST_TEST(value == expectedValue);
}
```

It doesn't happen if I rewrite it like this:
```C++
constexpr bool ExpectedValues[] = { false, true, true, true, false, false};
auto DataValues = boost::unit_test::data::make({ false, true, true, true, false, false });
BOOST_DATA_TEST_CASE(BoostDataTest2
	,  DataValues ^
	  boost::unit_test::data::make(ExpectedValues)
	, value, expectedValue)
{
	BOOST_TEST(value == expectedValue);
}
```

**Comment by b-spencer** [comment]
This appears to happen because the `boost::unit_test::data::monomorphic::init_list<bool>` specialization that captures the data set uses a `vector<bool>` itself.  Thus, its iterators dereference to a proxy type that only references the original value from the initial data set, and it is those proxies that get captured in the bound function during test setup.

One fix that seems to work is to introduce a wrapper structure inside `init_list<bool>` with a bool conversion operator, and then store the data set in a vector of that instead.  Its iterators return non-proxy values, and then it should work.

**Comment by raffienficiaud** [comment]
Thanks for the hints, it helped a lot. I've made a fix in the branch `topic/GH-217-init-list-boolean`, it would be great if you can test it.

**Comment by b-spencer** [comment]
Great!  I will take a look and try it.  It might be a few days, though.

**Comment by b-spencer** [comment]
The fix on that topic branch seems to work for me.  Thanks!

**Comment by raffienficiaud** [comment]
In master, closing.
