### ISSUE TITLE
Undefined symbols for architecture x86_64:   "vtable for boost::unit_test::unit_test_log_t"

### ISSUE THREAD

**Issue by nsquangexception** [boostorg/test#243]
I can use many Boost libs, but always failed with boost/test while building with Xcode on MacOS
MACOSX_DEPLOYMENT_TARGET=10.13
issue message:
Undefined symbols for architecture x86_64:
  "vtable for boost::unit_test::unit_test_log_t", referenced from:
      boost::unit_test::unit_test_log_t::unit_test_log_t() in main.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
ld: symbol(s) not found for architecture x86_64

**Comment by raffienficiaud** [comment]
Hi, sorry to hear that!

(thanks @Lastique and @mclow for forwarding the ticket.)

I use myself Xcode together with Boost.Test on a regular basis, my feeling is that this is an Xcode configuration issue. 
I will ask some questions in order to understand where the problem comes from. 

1. the scenario is you build boost.test with `b2`, then you have a project in Xcode and you try to link to the libraries of boost.test that was generated before. Is that correct?
1. how is the Xcode project being defined? Is that manually or with a tool like CMake?
1. what are the compiler defines for the test module?
1. would someone please share the command line of the linker emitted by Xcode?
1. would someone please share a minimal example reproducing the issue?

**Comment by raffienficiaud** [comment]
@nsquangexception any update ?

**Comment by raffienficiaud** [comment]
@nsquangexception @developer-mayuan Any update welcome.
