### ISSUE TITLE
Uninitialized memory in framework_init_observer_t

### ISSUE THREAD

**Issue by Barath-Kannan** [boostorg/test#272]
test_framework_init_observer.hpp:51

should be;
`bool m_has_failure{ false };`

This was causing errors in empty tests in gcc 9.1 and clang 8.0.1 at impl/framework.ipp:1672
`if( local_init_observer.has_failed() )`

**Comment by gouriano** [comment]
It seems there is a much bigger problem with that.
While the framework is supposed to call "framework_init_observer_t::test_start", which initializes m_has_failure,
it calls base class function "test_observer::test_start" instead (I use GCC 7.3.0).
I do not know where the problem is.
Also, on Windows/VisualStudio2019 it works correctly - framework_init_observer_t::test_start is called.
